#ifndef EEPROMLAYOUT_H
#define EEPROMLAYOUT_H

#include <EEPROM.h>

enum EepromLayout {
EEPROM_BRIGHTNESS_ADDR = 0,
EEPROM_BEEP_ADDR,
EEPROM_DN_INTERVAL1_MIN_ADDR,
EEPROM_DN_INTERVAL1_SEC_ADDR,
EEPROM_NT_INTERVAL1_MIN_ADDR,
EEPROM_NT_INTERVAL1_SEC_ADDR,
EEPROM_NT_INTERVAL2_MIN_ADDR,
EEPROM_NT_INTERVAL2_SEC_ADDR,
};

#endif