#ifndef EEPROMLAYOUT_H
#define EEPROMLAYOUT_H

#include <EEPROM.h>

enum EepromLayout {
EEPROM_DO_NOT_SAVE = -1,
EEPROM_BRIGHTNESS_ADDR = 0,
EEPROM_BEEP_ADDR = 1,
EEPROM_UP_ADDR = 10,
EEPROM_UP_RD_ADDR = 20,
EEPROM_DN_ADDR = 30,
EEPROM_NT_ADDR = 40
};

#endif